-- Test users with hashed passwords (Test123!)
-- Password hash for 'Test123!': $2b$10$YourHashHere... (will be generated by backend)

-- Note: Run this after schema.sql and seed.sql
-- Passwords will be hashed by the application, these are placeholders

-- Insert test users (passwords will be hashed: Test123! for all except admin: Admin123!)
-- The actual password hashing will be done through the API registration

-- System admin
-- Email: admin@moamalaty.iq
-- Password: Admin123!

-- Supervisor
-- Email: supervisor@gov.iq
-- Password: Test123!

-- Government employee
-- Email: employee@gov.iq
-- Password: Test123!

-- Legal advisor
-- Email lawyer@moamalaty.iq
-- Password: Test123!

-- Citizen
-- Email: citizen@test.com
-- Password: Test123!

-- This file is for documentation purposes
-- Actual user creation will be handled by the backend API with proper password hashing
